import javax.swing.JOptionPane;

/**
 * 
 */

/**
 * @author Jerome
 *
 */
public class OptionPanes {
/*
	public OptionPanes(SudokuBoard sBoard){
		board = sBoard;
	}*/
	
	public int closedOption(){
		return JOptionPane.CLOSED_OPTION;
	}
	
	public int chooseLevel(){
		
		String[] buttons = {"Easy", "Medium", "Hard", "Exit" };
		difficulty = JOptionPane.showOptionDialog(null, "To start, choose your difficulty:", "Welcome to Sudoku Fun!",
		        JOptionPane.PLAIN_MESSAGE, 0, null, buttons, buttons[3]);
		/*
		 * 
		 * difficulty value is automatically generated by JOptionPane buttons (can't change it due to how it's laid out)
		 * EASY =0, MEDIUM =1, HARD =2, EXIT_VALUE =3 pending user input
		 * in order to line up with difficulty constants in SudokuBoard Class
		 * Offset difficulty value by +1
		 *
		 */
		return difficulty + OFFSET;
	
	}
	
	public boolean exitMessageStart(){
		value = JOptionPane.showConfirmDialog(null,"So soon? Are you sure?", "Aurevoir Sudoku Fun!",
		        JOptionPane.YES_NO_OPTION);
		if(value == JOptionPane.YES_NO_OPTION)
			return true;
		else return false;
	}
	
	public boolean exitMessageInGame(){
		value = JOptionPane.showConfirmDialog(null, "Really? Your progress will not be saved.", "Aurevoir Sudoku Fun!",
		        JOptionPane.YES_NO_OPTION);
		if(value == JOptionPane.YES_OPTION)
			return true;
		else return false;
	}
	
	private final int OFFSET = 1;
	private int difficulty;
	private int value;
}
